# Site settings
title: The World Within
email: 
description: > # this means to ignore newlines until "baseurl:"
  NC's personal site for recording various thoughts and reflections.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nglchow.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  

# Build settings
markdown: kramdown
